# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "controllers", to: "controllers/index.js"
# pin_all_from "app/javascript/controllers", under: "controllers"
pin "controllers/application", to: "controllers/application.js"
pin "controllers/hello_controller", to: "controllers/hello_controller.js"
pin "controllers/dropdown_controller", to: "controllers/dropdown_controller.js"
pin "controllers/mobile_menu_controller", to: "controllers/mobile_menu_controller.js"
pin "controllers/testimonials_controller", to: "controllers/testimonials_controller.js"
pin "controllers/bunk_editor_controller", to: "controllers/bunk_editor_controller.js"
pin "controllers/reservation_form_controller", to: "controllers/reservation_form_controller.js"
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"
